jobapp/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resume_cv.urls'))
]

urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume_cv/urls.py
from django.urls import path

from .views import (
    TemplateListView,
    ResumeCVCreateView,
    resume_builder,
    load_builder,
)

app_name = "resume_cv"

urlpatterns = [
    path("templates", TemplateListView.as_view(), name="templates"),
    path("resume-cv/create", ResumeCVCreateView.as_view(), name="create"),
    path("templates/builder/<code>", resume_builder, name="builder"),
]

accounts/models.py
from django.db import models

# Create your models here.

resume_cv/models.py
from time import strftime
from django.contrib.auth import get_user_model


from django.db import models
import uuid

# from accounts.models import User
from utils.filename import generate_file_name

User = get_user_model()
def resume_cv_directory_path(instance, filename):
    return 'resumes/{0}/{1}'.format(strftime('%Y/%m/%d'), generate_file_name() + '.' + filename.split('.')[-1])


class ResumeCvCategory(models.Model):
    name = models.CharField(max_length=255)
    thumbnail = models.ImageField(upload_to=resume_cv_directory_path, blank=True, null=True)
    color = models.CharField(max_length=20)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ResumeCvTemplate(models.Model):
    category = models.ForeignKey(ResumeCvCategory, on_delete=models.CASCADE, related_name="templates")
    name = models.CharField(max_length=255)
    thumbnail = models.ImageField(upload_to=resume_cv_directory_path, blank=True, null=True)
    content = models.TextField(null=True, blank=True)
    style = models.TextField(null=True, blank=True)
    active = models.BooleanField(default=False)
    is_premium = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ResumeCv(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="resume_cvs")
    template = models.ForeignKey(ResumeCvTemplate, on_delete=models.CASCADE, related_name="resume_cvs")
    code = models.UUIDField(default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    content = models.TextField(null=True, blank=True)
    style = models.TextField(null=True, blank=True)
    is_published = models.BooleanField(default=True)
    view_count = models.IntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

resume_cv/forms.py
from django import forms

from resume_cv.models import ResumeCv


class ResumeCvForm(forms.ModelForm):
    class Meta:
        model = ResumeCv
        exclude = ("user", "view_count", "is_published")

accounts/views.py
from django.shortcuts import render

# Create your views here.

resume_cv/views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, JsonResponse
from django.middleware.csrf import get_token
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView

# Create your views here.
# from jobsapp.mixins import EmployeeRequiredMixin
from resume_cv.forms import ResumeCvForm
from resume_cv.models import ResumeCvTemplate, ResumeCvCategory, ResumeCv


class TemplateListView(ListView):
    """
    Get list of templates to create resume/cv
    """
    model = ResumeCvTemplate
    context_object_name = "templates"
    template_name = "resumes/templates.html"

    def get_queryset(self):
        return self.model.objects.filter(active=True)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['categories'] = ResumeCvCategory.objects.all()
        return data

class ResumeCVCreateView( View):

# class ResumeCVCreateView(LoginRequiredMixin, EmployeeRequiredMixin, View):
    """
    Create resume/cv
    """
    form_class = ResumeCvForm

    def post(self, request):
        f = ResumeCvForm(request.POST)
        if f.is_valid():
            f.instance.user = request.user
            r = f.save()
            return redirect(reverse_lazy("resume_cv:builder", kwargs={"code": r.code}))
        else:
            print(f.errors)
            return redirect(reverse_lazy("resume_cv:templates"))


def resume_builder(request, code):
    """
    Resume builder
    """
    # resume = ResumeCv.objects.get(code=code)
    templates = ResumeCvTemplate.objects.all()
    # token = get_token(request)
    return render(request, "resumes/builder.html", {"templates":templates})


def update_builder(request, id):
    """
    Resume builder
    """
    resume = ResumeCv.objects.get(id=id)
    if resume:
        data = json.loads(request.body)
        resume.content = data.get('gjs-html')
        resume.style = data.get('gjs-css')
        resume.save()
        return JsonResponse({
            'success': "Updated successfully",
        }, safe=True)
    return JsonResponse({
        'error': "No resume found",
    }, safe=True)


def load_builder(request, id):
    """
    Load builder
    """
    resume = ResumeCv.objects.get(id=id)
    if resume:
        return JsonResponse({
            'gjs-html': resume.content if resume.content else resume.template.content,
            'gjs-css': resume.style if resume.style else resume.template.style
        }, safe=True)
    else:
        return JsonResponse({
            'error': "No template found",
        }, safe=True)

templates/accounts/employee/register.html
{% extends 'base.html' %}
{% block title %}
    Employee Register
{% endblock %}

{% block content %}

    <div class="col-lg-6 offset-3 mt-3">
        <div class="box">
            <h3 class="heading">New account for employee</h3>
            <p class="lead">Not our registered yet?</p>
            <p class="text-muted">If you have any questions, please feel free to <a href="#">contact us</a>,
                our customer service center is working for you 24/7.</p>
            {% if form.errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name == 'gender' %}

                        <div class="form-group">
                            <label for="gender">Gender</label>
                            <br>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="gender" id="male gender"
                                       value="male">
                                <label class="form-check-label" for="male">Male</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="gender" id="female"
                                       value="female">
                                <label class="form-check-label" for="female">Female</label>
                            </div>
                        </div>
                        {% for error in field.errors %}
                            <div class="alert alert-danger alert-dismissable">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}

                    {% else %}

                        <div class="form-group">
                            <label for="id_{{ field.name }}">{{ field.label }}</label>
                            <input type="{{ field.field.widget.input_type }}"
                                   class="form-control"
                                   name="{{ field.name }}"
                                   id="id_{{ field.name }}"
                                   placeholder="{{ field.field.widget.attrs.placeholder }}">
                            {% for error in field.errors %}
                                <div class="alert alert-danger alert-dismissable">
                                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        </div>

                    {% endif %}
                {% endfor %}
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-white-primary"><i class="fa fa-user-md"></i> Register
                    </button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/accounts/employer/register.html
{% extends 'base.html' %}
{% block title %}
    Employer Register
{% endblock %}

{% block content %}

    <div class="col-lg-6 offset-3 mt-3">
        <div class="box">
            <h3 class="heading">New account for employers</h3>
            <p class="lead">Not our registered yet?</p>
            <p class="text-muted">If you have any questions, please feel free to <a href="#">contact us</a>,
                our customer service center is working for you 24/7.</p>
            {% if form.errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="id_{{ field.name }}">{{ field.label }}</label>
                        <input type="{{ field.field.widget.input_type }}"
                               class="form-control"
                               name="{{ field.name }}"
                               id="id_{{ field.name }}"
                               placeholder="{{ field.field.widget.attrs.placeholder }}">
                        {% for error in field.errors %}
                            <div class="alert alert-danger alert-dismissable">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-white-primary"><i class="fa fa-user-md"></i> Register
                    </button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}
    {{ title }}
{% endblock %}

{% block content %}

    <div class="col-lg-6 offset-3 mt-3">
        <div class="box">
            <h3 class="heading">Login</h3>
            <p class="lead">Already our have account?</p>
            {% if form.errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="id_{{ field.name }}">{{ field.label }}</label>
                        <input type="{{ field.field.widget.input_type }}"
                               class="form-control"
                               name="{{ field.name }}"
                               id="id_{{ field.name }}"
                               placeholder="{{ field.field.widget.attrs.placeholder }}">
                        {% for error in field.errors %}
                            <div class="alert alert-danger alert-dismissable">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-white-primary"><i class="fa fa-sign-in"></i> Log in
                    </button>
                    <br>
                    <div class="btn btn-outline-white-primary btn-sm" style="border-color:black">
                        <a href="{% url "social:begin" "facebook" %}" style="color:black"><i
                                class="fa fa-facebook-square"></i>Login with Facebook </a>
                    </div>
                    <div class="btn btn-outline-white-primary btn-sm" style="border-color:black">
                        <a href="{% url "social:begin" "google-oauth2" %}" style="color:black"><i
                                class="fa fa-google-plus-square"></i>Login with Google </a>
                    </div>
                    <div class="btn btn-outline-white-primary btn-sm" style="border-color:black">
                        <a href="{% url "social:begin" "linkedin-oauth2" %}" style="color:black"><i
                                class="fa fa-linkedin-square"></i>Login with Linkedin </a>
                    </div>
                    <div class="btn btn-outline-white-primary btn-sm" style="border-color:black">
                        <a href="{% url "social:begin" "github" %}" style="color:black"><i
                                class="fa fa-github-square"></i>Login with Github </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}
    Home
{% endblock %}

{% block content %}

    <section class="job-form-section job-form-section--image">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job-form-box">
                        <h2 class="heading">Find a <span class="accent">job</span> you will
                            <span class="accent">love</span>.
                        </h2>
                        <form id="job-main-form" method="get" action="{% url 'jobs:search' %}" class="job-main-form">
                            <div class="controls">
                                <div class="row align-items-center">
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="profession">{% trans 'Position' %}</label>
                                            <input type="text" id="profession" name="position"
                                                   placeholder="Position you are looking for" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="location">Location</label>
                                            <input type="text" id="location" name="location"
                                                   placeholder="Any particular location?" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <button type="submit"
                                                class="btn btn-outline-white-primary job-main-form__button">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="bg-light-gray">
        <div class="container">
            <h3 class="heading">Featured jobs</h3>
            <div class="row featured align-items-stretch">
                {% for job in jobs %}
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="box-image-text bg-visible full-height">
                            <div class="top">
                                <a href="#">
                                    <div class="image">
                                        <img src="{% static 'img/featured1.jpg' %}" alt="" class="img-fluid">
                                    </div>
                                    <div class="bg"></div>
                                    <div class="logo">
                                        <img src="{% static 'img/company-1.png' %}" alt="" style="max-width: 80px;">
                                    </div>
                                </a>
                            </div>
                            <div class="content">
                                <h5><a href="{% url 'jobs:jobs-detail' job.id %}">{{ job.title }}</a></h5>
                                <p class="featured__details"><i class="fa fa-map-marker job__location"></i>
                                    {{ job.location }}
                                    {% if job.type == '1' %}
                                        <span class="badge featured-badge badge-success">Full time</span>
                                    {% elif job.type == '2' %}
                                        <span class="badge featured-badge badge-primary">Part time</span>
                                    {% else %}
                                        <span style="color: #ffffff;" class="badge featured-badge badge-warning">Internship</span>
                                    {% endif %}
                                </p>
                                {% for tag in job.tags.all %}
                                    <span style="color: #ffffff;"
                                          class="badge featured-badge badge-secondary">{{ tag.name }}</span>
                                {% endfor %}
                                <p>{{ job.description | truncatewords_html:30 | safe }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <h4 class="heading">Trending this month</h4>
            {% for trending in trendings %}
                <div class="job-listing  job-listing--last">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">
                                <div class="col-2">
                                    <img src="{% static 'img/company-1.png' %}"
                                         alt="ShareBoardd " class="img-fluid">
                                </div>
                                <div class="col-10">
                                    <h4 class="job__title">
                                        <a href="{% url 'jobs:jobs-detail' trending.id %}">{{ trending.title }}</a>
                                    </h4>
                                    <p class="job__company">
                                        {{ trending.company_name }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-10 col-md-3 col-lg-2 ml-auto"><i class="fa fa-map-marker job__location"></i>
                            {{ trending.location }}
                        </div>
                        <div class="col-10 col-md-3 col-lg-3 ml-auto">
                            <p>Posted {{ trending.created_at|timesince }}</p>
                        </div>
                        <div class="col-sm-12 col-md-2 col-lg-1">
                            <div class="job__star">
                                <a href="#" data-toggle="tooltip" data-placement="top"
                                   title="Save to favourites" class="job__star__link">
                                    <i class="fa fa-star"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
    <section class="section-divider">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Start searching for your new job now! </p>
                    <p><a href="{% url 'jobs:jobs' %}" class="btn btn-outline-light">See our job offers </a></p>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/details.html
{% extends 'base.html' %}
{% load static %}
{% load is_already_applied %}
{% load humanize %}
{% block title %}
    Job details
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <h1 class="heading">{{ job.title }}<br>
                <small>at <a href="#"> {{ job.company_name }}</a></small>
            </h1>
            <div class="job-detail-description"><i class="fa fa-map-marker job__location"> </i>
		    {{ job.location }} | Posted {{ job.created_at|timesince }} ({{ job.created_at }}) |
                {% if job.type == '1' %}
                    <span class="badge featured-badge badge-success">Full time</span>
                {% elif job.type == '2' %}
                    <span class="badge featured-badge badge-primary">Part time</span>
                {% else %}
                    <span style="color: #ffffff;" class="badge featured-badge badge-warning">Internship</span>
                {% endif %}
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <h3>Category: {{ job.category }}</h3>
                    <h5>Last date: {{ job.last_date|date }}</h5>
                    <h5 class="text-info">Salary: {% if job.salary > 0 %} {{ job.salary | intcomma}}/Monthly {% else %} Negotiable {% endif %} </h5>
                    Tags:
                    {% for tag in job.tags.all %}
                        <span style="color: #ffffff;" class="badge featured-badge badge-secondary">{{ tag.name }}</span>
                    {% endfor %}
                    <blockquote class="blockquote">
                        <p>{{ job.description | safe }}</p>
                    </blockquote>
                    <div class="job-detail__apply-bottom">
                        {% if request.user.is_authenticated %}
                            {% is_already_applied job request.user as is_applied %}
                            {% if is_applied %}
                                <input type="button" class="btn btn-outline-white-primary" value="Already applied"/>
                            {% else %}
                                <form action="{% url 'jobs:apply-job' job.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="job" value="{{ job.id }}">
                                    <input type="submit" class="btn btn-outline-white-primary"
                                           value="Apply for this job"/>
                                </form>
                            {% endif %}
                        {% else %}
                            <form action="{% url 'jobs:apply-job' job.id %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="job" value="{{ job.id }}">
                                <input type="submit" class="btn btn-outline-white-primary"
                                       value="Apply for this job"/>
                            </form>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-1"></div>
                <div class="col-lg-3">
                    <h4>About {{ job.company_name }}</h4>
                    <p class="job-detail__company-description">{{ job.company_description }}</p>
                    <p class="job-detail__social social social--outline">
                        <a href="{{ job.website }}" data-toggle="tooltip" data-placement="top" title="Website"
                           class="link">
                            <i class="fa fa-link"></i>
                        </a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter" class="twitter">
                            <i class="fa fa-twitter"></i>
                        </a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook" class="facebook">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </p>
                    <div class="job-detail__apply-top">
                        {% if is_applied %}
                            <input type="button" class="btn btn-outline-white-primary" value="Already applied"/>
                        {% else %}
                            <form action="{% url 'jobs:apply-job' job.id %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="job" value="{{ job.id }}">
                                <input type="submit" class="btn btn-outline-white-primary" value="Apply for this job"/>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/resumes/templates.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    All templates
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/templates.css' %}"/>
{% endblock %}

{% block content %}

    <section class="mt-4">
        <div class="container">
            <h2 class="text-center">Choose a template for your Resume/CV</h2>
            <a href="{% url 'resume_cv:templates' %}" class="btn btn-sm btn-danger">All Templates</a>
            {% for category in categories %}
                <a href="{% url 'resume_cv:templates' %}" class="btn btn-sm btn-success">{{ category.name }}</a>
            {% endfor %}

            <div class="row mt-2">
                {% for template in templates %}
                    <div class="col-md-4">
                        <div class="clearfix blog-bottom blog blogitemlarge">
                            <a href="#" data-id="{{ template.id }}" data-toggle="modal" data-target="#createModal" title="Resume 8"
                               class="btn_builder_template image-blog date clearfix">
                                <img src="{{ template.thumbnail.url }}"
                                     alt="{{ template.name }}"
                                     data-was-processed="true" class="">
                                <span class="post-date badge badge-success"> Free</span>
                            </a>
                            <div class="content_blog clearfix flex flex-column flex-lg-row">
                                <div class="p-1">
                                    {{ template.name }}
                                </div>
                                <div class="d-flex pt-1">
                                    <a href="#" class="btn btn-sm btn-primary mr-2 btn_builder_template" data-id="{{ template.id }}"
                                       data-toggle="modal" data-target="#createModal">Builder</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">New Resumecv</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form id="" action="{% url 'resume_cv:create' %}" method="post">
                        {% csrf_token %}
                        <div class="modal-body">
                            <div class="form-group">
                                <input type="number" class="form-control" name="template" hidden required
                                       id="template_id_builder">
                                <label for="name" class="col-form-label">Name:</label>
                                <input type="text" class="form-control" name="name" required="" id="page-name">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary btn-sm" id="saveandbuilder">Save & Builder
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}